name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: Steenroder
  GITHUB_REPOSITORY: Steenroder/steenroder
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

on:
  push:
    branches: [ publish ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:

      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone -b publish "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: "docs/build_site.sh"
        shell: bash
