name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: Steenroder
  GITHUB_REPOSITORY: Steenroder/steenroder
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

on:
  push:
    branches: [ publish ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sphinx-toolbox/sphinx-action@master
        with:
          pre-build-command: "pip install .[docs]"
          docs-folder: "docs/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/publish'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
