name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: Steenroder
  GITHUB_REPOSITORY: Steenroder/steenroder
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

on:
  push:
    branches: [ publish_nb ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-xdist nbmake
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test notebooks with pytest
      run: |
        pytest --nbmake --overwrite -n=auto notebooks/squares.ipynb
        mkdir -p docs/_notebooks
        mv notebooks/squares.ipynb docs/
    - name: Build documentation
      - uses: sphinx-toolbox/sphinx-action@master
        with:
          pre-build-command: "python -m pip install .[docs]"
          docs-folder: "docs/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/publish_nb'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
