# This workflow will install Python dependencies and run notebooks

name: Python integration

on:
  push:
    branches: [ publish_nb ]
  pull_request:
    branches: [ publish_nb ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-xdist nbmake
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test notebooks with pytest
      run: |
        pytest --nbmake --overwrite -n=auto notebooks/squares.ipynb
